# Generated by Django 5.0.1 on 2024-01-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FrontButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InsideFragment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="asset/images/"),
                ),
                ("title", models.TextField()),
                (
                    "frontbutton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codemodel.frontbutton",
                    ),
                ),
            ],
        ),
    ]
