# Generated by Django 5.0.1 on 2024-01-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemodel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="asset/images/"),
                ),
                ("url_image", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "front_button",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codemodel.frontbutton",
                    ),
                ),
            ],
        ),
    ]
