# Generated by Django 5.0.1 on 2024-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemodel", "0003_frontbutton_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="insidefragment",
            name="nomor",
            field=models.IntegerField(default=-1),
        ),
    ]
