# Generated by Django 5.0.1 on 2024-01-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemodel", "0004_insidefragment_nomor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/src/main/res/drawable/"
            ),
        ),
        migrations.AlterField(
            model_name="frontbutton",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/src/main/res/drawable/"
            ),
        ),
        migrations.AlterField(
            model_name="insidefragment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/src/main/res/drawable/"
            ),
        ),
    ]
