# Generated by Django 5.0.1 on 2024-07-11 15:14

import codemodel.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codemodel", "0005_alter_definition_image_alter_frontbutton_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="program_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="frontbutton",
            name="program_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="insidefragment",
            name="program_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="definition",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=codemodel.models.lowercase_filename
            ),
        ),
        migrations.AlterField(
            model_name="frontbutton",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=codemodel.models.lowercase_filename
            ),
        ),
        migrations.AlterField(
            model_name="insidefragment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=codemodel.models.lowercase_filename
            ),
        ),
    ]
