# Generated by Django 5.0.1 on 2024-08-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codemodel", "0006_definition_program_name_frontbutton_program_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insidefragment",
            name="frontbutton",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="codemodel.frontbutton"
            ),
        ),
    ]
