# Generated by Django 5.0.1 on 2024-08-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codemodel", "0007_alter_insidefragment_frontbutton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="front_button",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="codemodel.frontbutton"
            ),
        ),
        migrations.AlterField(
            model_name="insidefragment",
            name="frontbutton",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="codemodel.frontbutton"
            ),
        ),
    ]
